---

name: Report the GitHub References
on:
  push:
  workflow_dispatch:
jobs:
  report-references:
    runs-on: ubuntu-latest # note to self: find a real, debian, runner
    steps:
      - name: Checkout out the repository itself
        uses: actions/checkout@v4
      - name: Get the listing of the GITHUB_WORKSPACE
        run: ls -la $GITHUB_WORKSPACE
      - name: Get the whole tree, why not?
        run: tree $PWD
      - name: Report the references
        run: $GITHUB_WORKSPACE/.github/workflows/report.sh
      - name: Set the env name
        run: echo "K8S_DEPLOY_ENVIRONMENT=$($GITHUB_WORKSPACE/.github/workflows/get-k8s-environment.sh)" >> "$GITHUB_ENV"
      - name: Report the k8s env
        run: echo K8S_DEPLOY_ENVIRONMENT=$K8S_DEPLOY_ENVIRONMENT
      - name: Report, using env.K8S_DEPLOY_ENVIRONMENT
        run: echo K8S_DEPLOY_ENVIRONMENT=${{ env.K8S_DEPLOY_ENVIRONMENT }}
