---

name: Report the GitHub References
on:
  push:
  workflow_dispatch:
jobs:
  report-references:
    runs-on: ubuntu-latest # note to self: find a real, debian, runner
    steps:
      - name: Report the references
        run: echo "GITHUB_REF=$GITHUB_REF\nGITHUB_REF_NAME-$GITHUB_REF_NAME"
