---

name: Report the GitHub References
on:
  push:
  workflow_dispatch:
jobs:
  report-references:
    runs-on: ubuntu-latest # note to self: find a real, debian, runner
    steps:
      - name: Checkout out the repository itself
        uses: actions/checkout@v4
      - name: Get the listing of the GITHUB_WORKSPACE
        run: ls -la $GITHUB_WORKSPACE
      - name: Get the whole tree, why not?
        run: tree $PWD
      - name: Report the references
        run: $GITHUB_WORKSPACE/.github/workflows/report.sh
